stone-LDDTestingOverview.pptx: LDDTestingOverview.md images/common/*.png images/overview/*.png
	pandoc -o stone-LDDTestingOverview.pptx LDDTestingOverview.md
stone-LDDTestingTechniques.pptx: LDDTestingTechniques.md images/common/*.png images/techniques/*.png
	pandoc -o stone-LDDTestingTechniques.pptx LDDTestingTechniques.md
